runtime: python27
api_version: 1
threadsafe: yes

handlers:

# Resources
- url: /(.*\.html)
  static_files: dist/angular8-ci-cd-example/\1
  upload: dist/angular8-ci-cd-example/(.*\.html)

# Resources
- url: /(.*\.(gif|png|jpg|css|js)(|\.map))$
  static_files: dist/angular8-ci-cd-example/\1
  upload: dist/angular8-ci-cd-example/(.*)(|\.map)

# Fonts
- url: /(.*\.(ttf|woff2|woff)(|\.map))$
  mime_type: font/opentype
  static_files: dist/angular8-ci-cd-example/\1
  upload: dist/angular8-ci-cd-example/(.*)(|\.map)

# Site root.
- url: /
  static_files: dist/angular8-ci-cd-example/index.html
  upload: dist/angular8-ci-cd-example/index.html

# Catch-all rule, responsible from handling Angular application routes (deeplinks).
- url: /.*
  static_files: dist/angular8-ci-cd-example/index.html
  upload: dist/angular8-ci-cd-example/index.html

skip_files:
- ^(?!dist)