steps:
- name: 'gcr.io/cloud-builders/npm:node-10.10.0'
  id: 'Install'
  args: [ install ]

- name: 'gcr.io/cloud-builders/npm:node-10.10.0'
  id: 'Prod build'
  args: [ run, build, --prod ]

- name: gcr.io/cloud-builders/gcloud
  args: [ app, deploy ]